import type { CreatePoiDto } from "@poi/shared";

export const SEED_POIS: CreatePoiDto[] = [
  {
    type: "restaurant",
    name: "Harbor Bistro",
    location: { type: "Point", coordinates: [24.9384, 60.1699] },
    address: "Pohjoisesplanadi 1, Helsinki",
  },
  {
    type: "restaurant",
    name: "Kallio Kitchen",
    location: { type: "Point", coordinates: [24.9508, 60.1841] },
    address: "Vaasankatu 12, Helsinki",
  },
  {
    type: "gas_station",
    name: "Ruoholahti Fuel Stop",
    location: { type: "Point", coordinates: [24.9147, 60.1613] },
    address: "Itamerenkatu 5, Helsinki",
    hasGasoline: true,
    hasElectricCharging: false,
    hasRestaurant: false,
  },
  {
    type: "gas_station",
    name: "Pasila Travel Center",
    location: { type: "Point", coordinates: [24.9327, 60.1985] },
    address: "Ratapihantie 9, Helsinki",
    hasGasoline: true,
    hasElectricCharging: true,
    hasRestaurant: true,
  },
  {
    type: "gas_station",
    name: "Viikki EV Charging",
    location: { type: "Point", coordinates: [25.0193, 60.2265] },
    address: "Viikinkaari 2, Helsinki",
    hasGasoline: false,
    hasElectricCharging: true,
    hasRestaurant: false,
  },
  {
    type: "camping",
    name: "Rastila Camping",
    location: { type: "Point", coordinates: [25.0989, 60.1935] },
    address: "Karavaanikatu 4, Helsinki",
    hasTentSites: true,
    hasCaravanSites: true,
  },
  {
    type: "accommodation",
    name: "Katajanokka Hotel",
    location: { type: "Point", coordinates: [24.9622, 60.1656] },
    address: "Merikasarminkatu 1, Helsinki",
    category: "hotel",
  },
  {
    type: "accommodation",
    name: "Kallio Backpackers Hostel",
    location: { type: "Point", coordinates: [24.9497, 60.1832] },
    address: "Fleminginkatu 9, Helsinki",
    category: "hostel",
  },
];
